### ISSUE TITLE
Decimal Format in Popup

### ISSUE THREAD

**Issue by ikojic000** [DJ-Raven/glasspane-popup#1]
Hi,

your use of DecimalFormat can depend on PC settings of a user. So it can put "," instead of "." for decimal separator.
`private final DecimalFormat df = new DecimalFormat("#.###");`

You can use this:
`private final DecimalFormat df = new DecimalFormat( "#.###" , DecimalFormatSymbols.getInstance( Locale.US ) );`
to avoid that bug.

**Comment by DJ-Raven** [comment]
Thank you
